# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\svgToolLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 380))
        MainWindow.setMaximumSize(QtCore.QSize(550, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 91))
        self.groupBox.setObjectName("groupBox")
        self.btnInputDir = QtWidgets.QPushButton(self.groupBox)
        self.btnInputDir.setGeometry(QtCore.QRect(440, 20, 81, 23))
        self.btnInputDir.setObjectName("btnInputDir")
        self.lineInputDir = QtWidgets.QLineEdit(self.groupBox)
        self.lineInputDir.setGeometry(QtCore.QRect(60, 20, 371, 23))
        self.lineInputDir.setReadOnly(True)
        self.lineInputDir.setObjectName("lineInputDir")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 23))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 41, 23))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineFilter = QtWidgets.QLineEdit(self.groupBox)
        self.lineFilter.setGeometry(QtCore.QRect(60, 50, 171, 23))
        self.lineFilter.setObjectName("lineFilter")
        self.labelFilter = QtWidgets.QLabel(self.groupBox)
        self.labelFilter.setGeometry(QtCore.QRect(240, 50, 171, 23))
        self.labelFilter.setText("")
        self.labelFilter.setObjectName("labelFilter")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(10, 110, 531, 121))
        self.groupBox2.setObjectName("groupBox2")
        self.btnOutputDir = QtWidgets.QPushButton(self.groupBox2)
        self.btnOutputDir.setGeometry(QtCore.QRect(440, 20, 81, 23))
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.lineOutputDir = QtWidgets.QLineEdit(self.groupBox2)
        self.lineOutputDir.setGeometry(QtCore.QRect(60, 20, 371, 23))
        self.lineOutputDir.setReadOnly(True)
        self.lineOutputDir.setObjectName("lineOutputDir")
        self.checkBoxIos = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBoxIos.setGeometry(QtCore.QRect(360, 50, 75, 22))
        self.checkBoxIos.setChecked(True)
        self.checkBoxIos.setObjectName("checkBoxIos")
        self.checkBoxAndroid = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBoxAndroid.setGeometry(QtCore.QRect(440, 50, 75, 22))
        self.checkBoxAndroid.setChecked(True)
        self.checkBoxAndroid.setObjectName("checkBoxAndroid")
        self.comboBoxMode = QtWidgets.QComboBox(self.groupBox2)
        self.comboBoxMode.setGeometry(QtCore.QRect(60, 50, 281, 22))
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.label_2 = QtWidgets.QLabel(self.groupBox2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 41, 22))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox2)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 41, 22))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox2)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 41, 22))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox2)
        self.label_7.setGeometry(QtCore.QRect(140, 80, 41, 22))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineWidth = QtWidgets.QLineEdit(self.groupBox2)
        self.lineWidth.setGeometry(QtCore.QRect(60, 80, 71, 23))
        self.lineWidth.setObjectName("lineWidth")
        self.lineHeight = QtWidgets.QLineEdit(self.groupBox2)
        self.lineHeight.setGeometry(QtCore.QRect(190, 80, 71, 23))
        self.lineHeight.setObjectName("lineHeight")
        self.checkBoxRatio = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBoxRatio.setGeometry(QtCore.QRect(280, 80, 161, 23))
        self.checkBoxRatio.setChecked(True)
        self.checkBoxRatio.setObjectName("checkBoxRatio")
        self.btnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.btnConvert.setGeometry(QtCore.QRect(10, 300, 75, 23))
        self.btnConvert.setObjectName("btnConvert")
        self.progressBarTotal = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarTotal.setGeometry(QtCore.QRect(10, 270, 421, 23))
        self.progressBarTotal.setProperty("value", 0)
        self.progressBarTotal.setObjectName("progressBarTotal")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(450, 240, 90, 90))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 330, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 240, 421, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(90, 300, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineInputDir, self.btnInputDir)
        MainWindow.setTabOrder(self.btnInputDir, self.lineFilter)
        MainWindow.setTabOrder(self.lineFilter, self.lineOutputDir)
        MainWindow.setTabOrder(self.lineOutputDir, self.btnOutputDir)
        MainWindow.setTabOrder(self.btnOutputDir, self.comboBoxMode)
        MainWindow.setTabOrder(self.comboBoxMode, self.checkBoxIos)
        MainWindow.setTabOrder(self.checkBoxIos, self.checkBoxAndroid)
        MainWindow.setTabOrder(self.checkBoxAndroid, self.lineWidth)
        MainWindow.setTabOrder(self.lineWidth, self.lineHeight)
        MainWindow.setTabOrder(self.lineHeight, self.checkBoxRatio)
        MainWindow.setTabOrder(self.checkBoxRatio, self.btnConvert)
        MainWindow.setTabOrder(self.btnConvert, self.btnCancel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flandre SVG Tool"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.btnInputDir.setText(_translate("MainWindow", "Browse..."))
        self.label.setText(_translate("MainWindow", "Path"))
        self.label_4.setText(_translate("MainWindow", "Filter"))
        self.groupBox2.setTitle(_translate("MainWindow", "Output"))
        self.btnOutputDir.setText(_translate("MainWindow", "Browse..."))
        self.checkBoxIos.setText(_translate("MainWindow", "iOS"))
        self.checkBoxAndroid.setText(_translate("MainWindow", "Android"))
        self.label_2.setText(_translate("MainWindow", "Path"))
        self.label_3.setText(_translate("MainWindow", "Preset"))
        self.label_6.setText(_translate("MainWindow", "Width"))
        self.label_7.setText(_translate("MainWindow", "Height"))
        self.checkBoxRatio.setText(_translate("MainWindow", "Maintain aspect ratio"))
        self.btnConvert.setText(_translate("MainWindow", "Convert"))
        self.label_5.setText(_translate("MainWindow", "Let me handle this human!"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

