# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\svgToolLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(550, 600))
        MainWindow.setMaximumSize(QtCore.QSize(550, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 221))
        self.groupBox.setObjectName("groupBox")
        self.btnInputDir = QtWidgets.QPushButton(self.groupBox)
        self.btnInputDir.setGeometry(QtCore.QRect(440, 30, 81, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInputDir.sizePolicy().hasHeightForWidth())
        self.btnInputDir.setSizePolicy(sizePolicy)
        self.btnInputDir.setMinimumSize(QtCore.QSize(0, 0))
        self.btnInputDir.setObjectName("btnInputDir")
        self.lineInputDir = QtWidgets.QLineEdit(self.groupBox)
        self.lineInputDir.setGeometry(QtCore.QRect(70, 30, 361, 23))
        self.lineInputDir.setReadOnly(True)
        self.lineInputDir.setObjectName("lineInputDir")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 41, 23))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(320, 60, 41, 23))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineFilter = QtWidgets.QLineEdit(self.groupBox)
        self.lineFilter.setGeometry(QtCore.QRect(370, 60, 151, 23))
        self.lineFilter.setObjectName("lineFilter")
        self.labelFilter = QtWidgets.QLabel(self.groupBox)
        self.labelFilter.setGeometry(QtCore.QRect(330, 170, 171, 23))
        self.labelFilter.setText("")
        self.labelFilter.setObjectName("labelFilter")
        self.listViewFiles = QtWidgets.QListView(self.groupBox)
        self.listViewFiles.setGeometry(QtCore.QRect(70, 60, 251, 151))
        self.listViewFiles.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listViewFiles.setObjectName("listViewFiles")
        self.btnRefresh = QtWidgets.QPushButton(self.groupBox)
        self.btnRefresh.setGeometry(QtCore.QRect(450, 120, 71, 23))
        self.btnRefresh.setObjectName("btnRefresh")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 41, 23))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.btnSelectAll = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectAll.setGeometry(QtCore.QRect(450, 90, 71, 23))
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.btnSelectNone = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectNone.setGeometry(QtCore.QRect(370, 90, 71, 23))
        self.btnSelectNone.setObjectName("btnSelectNone")
        self.labelSelected = QtWidgets.QLabel(self.groupBox)
        self.labelSelected.setGeometry(QtCore.QRect(330, 190, 171, 23))
        self.labelSelected.setText("")
        self.labelSelected.setObjectName("labelSelected")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(320, 90, 41, 23))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(10, 240, 531, 221))
        self.groupBox2.setObjectName("groupBox2")
        self.btnOutputDir = QtWidgets.QPushButton(self.groupBox2)
        self.btnOutputDir.setGeometry(QtCore.QRect(440, 30, 81, 23))
        self.btnOutputDir.setObjectName("btnOutputDir")
        self.lineOutputDir = QtWidgets.QLineEdit(self.groupBox2)
        self.lineOutputDir.setGeometry(QtCore.QRect(70, 30, 361, 23))
        self.lineOutputDir.setReadOnly(True)
        self.lineOutputDir.setObjectName("lineOutputDir")
        self.comboBoxMode = QtWidgets.QComboBox(self.groupBox2)
        self.comboBoxMode.setGeometry(QtCore.QRect(70, 60, 255, 23))
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.label_2 = QtWidgets.QLabel(self.groupBox2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 41, 22))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox2)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 41, 22))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 171, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 41, 22))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lineWidth = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineWidth.setGeometry(QtCore.QRect(60, 30, 91, 23))
        self.lineWidth.setObjectName("lineWidth")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 41, 22))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineHeight = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineHeight.setGeometry(QtCore.QRect(60, 60, 91, 23))
        self.lineHeight.setObjectName("lineHeight")
        self.checkBoxRatio = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxRatio.setGeometry(QtCore.QRect(10, 90, 161, 23))
        self.checkBoxRatio.setChecked(True)
        self.checkBoxRatio.setObjectName("checkBoxRatio")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox2)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 90, 131, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBoxIos = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxIos.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.checkBoxIos.setChecked(True)
        self.checkBoxIos.setObjectName("checkBoxIos")
        self.checkBoxXcassets = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxXcassets.setGeometry(QtCore.QRect(10, 60, 111, 22))
        self.checkBoxXcassets.setToolTip("")
        self.checkBoxXcassets.setChecked(True)
        self.checkBoxXcassets.setObjectName("checkBoxXcassets")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox2)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 90, 131, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBoxAndroid = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxAndroid.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.checkBoxAndroid.setChecked(True)
        self.checkBoxAndroid.setObjectName("checkBoxAndroid")
        self.checkBoxVS = QtWidgets.QCheckBox(self.groupBox2)
        self.checkBoxVS.setGeometry(QtCore.QRect(340, 60, 181, 23))
        self.checkBoxVS.setToolTipDuration(-1)
        self.checkBoxVS.setChecked(True)
        self.checkBoxVS.setObjectName("checkBoxVS")
        self.btnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.btnConvert.setGeometry(QtCore.QRect(10, 530, 91, 23))
        self.btnConvert.setObjectName("btnConvert")
        self.progressBarTotal = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarTotal.setGeometry(QtCore.QRect(10, 470, 421, 23))
        self.progressBarTotal.setProperty("value", 0)
        self.progressBarTotal.setObjectName("progressBarTotal")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(450, 470, 90, 90))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 560, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 500, 421, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(110, 530, 91, 23))
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineInputDir, self.btnInputDir)
        MainWindow.setTabOrder(self.btnInputDir, self.lineFilter)
        MainWindow.setTabOrder(self.lineFilter, self.lineOutputDir)
        MainWindow.setTabOrder(self.lineOutputDir, self.btnOutputDir)
        MainWindow.setTabOrder(self.btnOutputDir, self.comboBoxMode)
        MainWindow.setTabOrder(self.comboBoxMode, self.checkBoxVS)
        MainWindow.setTabOrder(self.checkBoxVS, self.lineWidth)
        MainWindow.setTabOrder(self.lineWidth, self.lineHeight)
        MainWindow.setTabOrder(self.lineHeight, self.checkBoxRatio)
        MainWindow.setTabOrder(self.checkBoxRatio, self.checkBoxIos)
        MainWindow.setTabOrder(self.checkBoxIos, self.checkBoxXcassets)
        MainWindow.setTabOrder(self.checkBoxXcassets, self.checkBoxAndroid)
        MainWindow.setTabOrder(self.checkBoxAndroid, self.btnConvert)
        MainWindow.setTabOrder(self.btnConvert, self.btnCancel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flandre SVG Tool"))
        self.groupBox.setTitle(_translate("MainWindow", "Input"))
        self.btnInputDir.setText(_translate("MainWindow", "Browse..."))
        self.label.setText(_translate("MainWindow", "Path"))
        self.label_4.setText(_translate("MainWindow", "Filter"))
        self.btnRefresh.setText(_translate("MainWindow", "Refresh"))
        self.label_8.setText(_translate("MainWindow", "Files"))
        self.btnSelectAll.setText(_translate("MainWindow", "All"))
        self.btnSelectNone.setText(_translate("MainWindow", "None"))
        self.label_9.setText(_translate("MainWindow", "Select"))
        self.groupBox2.setTitle(_translate("MainWindow", "Output"))
        self.btnOutputDir.setText(_translate("MainWindow", "Browse..."))
        self.label_2.setText(_translate("MainWindow", "Path"))
        self.label_3.setText(_translate("MainWindow", "Preset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Size"))
        self.label_6.setText(_translate("MainWindow", "Width"))
        self.label_7.setText(_translate("MainWindow", "Height"))
        self.checkBoxRatio.setText(_translate("MainWindow", "Maintain aspect ratio"))
        self.groupBox_3.setTitle(_translate("MainWindow", "iOS"))
        self.checkBoxIos.setText(_translate("MainWindow", "Export"))
        self.checkBoxXcassets.setText(_translate("MainWindow", "Use XCAssets"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Android"))
        self.checkBoxAndroid.setText(_translate("MainWindow", "Export"))
        self.checkBoxVS.setToolTip(_translate("MainWindow", "Warning: this may crash intelisense"))
        self.checkBoxVS.setText(_translate("MainWindow", "Update Solution"))
        self.btnConvert.setText(_translate("MainWindow", "Export"))
        self.label_5.setText(_translate("MainWindow", "Let me handle this human!"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

